### ISSUE TITLE
Suggestions for changes in abstract

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [adamrher/2017-physres#1]
- Acronyms in the abstract should be defined
- Mentioning 2x2 physics grid in abstract is likely hard for the reader to understand when 3x3 has not been defined (maybe not mention those details here).
- Abstract does not mention Aqua-planet simulations
- Since mapping back-and-forth between grids was a major challenge, it should probably also be mentioned

**Comment by adamrher** [comment]
i've incorporated these changes into the abstract, but am leaving this issue open in case you have additional feedback.

**Comment by PeterHjortLauritzen** [comment]
Look good. A couple of editorial comments on the abstract:
- first sentence. Shouldn't "This paper described ..." be "This paper describes ..."
- "The dry dynamics are" -> "The dry dynamics is"
