### ISSUE TITLE
Add third row to Figure 5 with low-order mapping simulation result

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [adamrher/2017-physres#6]

**Comment by adamrher** [comment]
Attached is the CLDLIQ field with low-order mapping in the third row (iwidth=1 and ifdef PCoM in fvm_mapping.F90). The differences are easier to see on the lat-lon contouring:
[temp_CLDLIQ.pdf](https://github.com/adamrher/2017-physres/files/2912008/temp_CLDLIQ.pdf)

but here is the raster version as well:
[temp_CLDLIQ_cellfill.pdf](https://github.com/adamrher/2017-physres/files/2912010/temp_CLDLIQ_cellfill.pdf)

So low-order pg2 looks very similar to default pg2. It is easier to see the differences in the l2norms:
[temp_l2.pdf](https://github.com/adamrher/2017-physres/files/2912037/temp_l2.pdf)

**Comment by PeterHjortLauritzen** [comment]
Thanks Adam ... OK ... so the FKESSLER case is too simple in terms of the feedback of physics on dynamics, i.e. we are just looking at mapping error from dyn2phys (which is similar to high-order mapping for a grid-scale field) and not really an effect of the reverse mapping (since it does not feed back on the dynamics much).
